### ISSUE TITLE
toggle button is not changing with FW 5.31.20

### ISSUE THREAD

**Issue by dymitar** [nachocinalli/adapt-toggleItems#1]
In version 1.1.0 the toggle button is not working with FW 5.31.20 (the toggle of the items is working)
looking in browser dev the .toggleitems__input:checked+.toggleitems__toggle-display does not apply for some reason

**Comment by dymitar** [comment]
Publishing the course and importing in LMS the toggle button is working. It is probably an issue with the authoring tool. V 0.11.1
Not an essential issue when you know it is working after publishing, I have not enough experience with the authoring tool to find the reason

**Comment by nachocinalli** [comment]
Thank you for the heads-up, I will check it out

**Comment by nachocinalli** [comment]
It seems that the issue starts in version 5.28.13 when adding core/js/fixes/safari.label.click.blur.js. I'm going to modify the toggle-items.less file so that it can work correctly:
```
.toggleitems {
  &__item.is-active  &__toggle-display {
    background-color: @blue;
    color: @white;
    &::before {
      transform: translate(100%, -50%);
    }
  }
}
```

**Comment by dymitar** [comment]
thank you, very fast reaction.
Your components are really good.
The colleagues asked me to update our system to be able to use more of them
Kind regards.
